KaOsPizzaPL/Components/TopMenuViewComponent.cs
using KaOsPizzaEL.IdentityModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace KaOsPizzaPL.Components
{
    public class TopMenuViewComponent : ViewComponent
    {
        public readonly UserManager<AppUser> _userManager;

        public TopMenuViewComponent(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public IViewComponentResult Invoke()
        {
            try
            {
                var username = User.Identity.Name;

                if (username != null)
                {
                    var user = _userManager.FindByNameAsync(username).Result;
                    return View(user);
                }
                return View(new AppUser());
            }
            catch (Exception ex)
            {
                return View(new AppUser());
            }
        }
    }
}

KaOsPizzaPL/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>ADMIN</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/admin/assets/img/favicon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/admin/assets/css/bootstrap.min.css">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="~/admin/assets/plugins/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/admin/assets/plugins/fontawesome/css/all.min.css">

    <!-- Feather CSS -->
    <link rel="stylesheet" href="~/admin/assets/css/feather.css">

    <!-- Datatables CSS -->
    <link rel="stylesheet" href="~/admin/assets/plugins/datatables/datatables.min.css">

    <!-- Datepicker CSS -->
    <link rel="stylesheet" href="~/admin/assets/css/bootstrap-datetimepicker.min.css">

    <!-- Main CSS -->
    <link rel="stylesheet" href="~/admin/assets/css/style.css">

</head>
<body>

    <!-- Main Wrapper -->
    <div class="main-wrapper">

        <!-- Header -->
        <div class="header">

            <!-- Logo -->
            <div class="header-left">
                <a href="index.html" class="logo">
                    <img src="~/admin/assets/img/logo.png" alt="Logo">
                </a>
                <a href="index.html" class="logo logo-small">
                    <img src="~/admin/assets/img/logo-small.png" alt="Logo" width="30" height="30">
                </a>
                <!-- Sidebar Toggle -->
                <a href="~/admin/javascript:void(0);" id="toggle_btn">
                    <i class="feather-chevrons-left"></i>
                </a>
                <!-- /Sidebar Toggle -->
                <!-- Mobile Menu Toggle -->
                <a class="mobile_btn" id="mobile_btn">
                    <i class="feather-chevrons-left"></i>
                </a>
                <!-- /Mobile Menu Toggle -->
            </div>
            <!-- /Logo -->

        </div>
        <!-- /Header -->
        <!-- Sidebar -->
        <div class="sidebar" id="sidebar">
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                        <li>
                            <a asp-controller="Admin" asp-action="Index">Admin<span class="sr-only" data-feather="home">(current)</span></a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="AddFood">Ürün Ekle<span class="sr-only" data-feather="clipboard">(current)</span></a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="Reservation">Rezervasyon<span class="sr-only" data-feather="user-check">(current)</span></a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="Confirmation">Rezervasyon Talepleri<span class="sr-only" data-feather="user-check">(current)</span></a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="ReservationSettings">Rezervasyon Ayarları<span class="sr-only" data-feather="user-check">(current)</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Sidebar -->
        @RenderBody()

    </div>
    <!-- /Main Wrapper -->
    <!-- jQuery -->
    <script src="~/admin/assets/js/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap Core JS -->
    <script src="~/admin/assets/js/bootstrap.bundle.min.js"></script>

    <!-- Feather Icon JS -->
    <script src="~/admin/assets/js/feather.min.js"></script>

    <!-- Slimscroll JS -->
    <script src="~/admin/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Datatables JS -->
    <script src="~/admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/admin/assets/plugins/datatables/datatables.min.js"></script>

    <!-- Datepicker Core JS -->
    <script src="~/admin/assets/js/moment.min.js"></script>
    <script src="~/admin/assets/js/bootstrap-datetimepicker.min.js"></script>

    <!-- Custom JS -->
    <script src="~/admin/assets/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

KaOsPizzaPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KaOsPizzaPL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KaOsPizzaPL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KaOsPizzaPL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
        
    </header>

    

    <div class="container">
        <main role="main" class="pb-3">
            @await Component.InvokeAsync("TopMenu")
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KaOsPizzaPL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KaOsPizzaPL/Views/Shared/_PizzaLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <title>KaOs Pizza</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do" rel="stylesheet">

    <link rel="stylesheet" href="~/pizza-gh-pages/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/pizza-gh-pages/css/animate.css">

    <link rel="stylesheet" href="~/pizza-gh-pages/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/pizza-gh-pages/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/pizza-gh-pages/css/magnific-popup.css">

    <link rel="stylesheet" href="~/pizza-gh-pages/css/aos.css">

    <link rel="stylesheet" href="~/pizza-gh-pages/css/ionicons.min.css">

    <link rel="stylesheet" href="~/pizza-gh-pages/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/pizza-gh-pages/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/pizza-gh-pages/css/flaticon.css">
    <link rel="stylesheet" href="~/pizza-gh-pages/css/icomoon.css">
    <link rel="stylesheet" href="~/pizza-gh-pages/css/style.css">
</head>
<body>


    @await Component.InvokeAsync("TopMenu")

    @RenderBody()

    <footer class="ftco-footer ftco-section img">
        <div class="overlay"></div>
        <div class="container">
            <div class="row mb-5">
                <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">About Us</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-5 mb-md-5">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Recent Blog</h2>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4" style="background-image: url(/pizza-gh-pages/images/image_1.jpg);"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4" style="background-image: url(/pizza-gh-pages/images/image_2.jpg);"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
                    <div class="ftco-footer-widget mb-4 ml-md-4">
                        <h2 class="ftco-heading-2">Services</h2>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">Cooked</a></li>
                            <li><a href="#" class="py-2 d-block">Deliver</a></li>
                            <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
                            <li><a href="#" class="py-2 d-block">Mixed</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


    <script src="~/pizza-gh-pages/js/jquery.min.js"></script>
    <script src="~/pizza-gh-pages/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/pizza-gh-pages/js/popper.min.js"></script>
    <script src="~/pizza-gh-pages/js/bootstrap.min.js"></script>
    <script src="~/pizza-gh-pages/js/jquery.easing.1.3.js"></script>
    <script src="~/pizza-gh-pages/js/jquery.waypoints.min.js"></script>
    <script src="~/pizza-gh-pages/js/jquery.stellar.min.js"></script>
    <script src="~/pizza-gh-pages/js/owl.carousel.min.js"></script>
    <script src="~/pizza-gh-pages/js/jquery.magnific-popup.min.js"></script>
    <script src="~/pizza-gh-pages/js/aos.js"></script>
    <script src="~/pizza-gh-pages/js/jquery.animateNumber.min.js"></script>
    <script src="~/pizza-gh-pages/js/bootstrap-datepicker.js"></script>
    <script src="~/pizza-gh-pages/js/jquery.timepicker.min.js"></script>
    <script src="~/pizza-gh-pages/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/pizza-gh-pages/js/google-map.js"></script>
    <script src="~/pizza-gh-pages/js/main.js"></script>

</body>
</html>